engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
  - "test/**/*"
