# Glue Framework
# Copyright (C) 2015 Joby Elliott
#
# This file is not licensed along with the rest of the Glue Framework. It is
# released into the public domain, and you are free to modify or re-use it
# in any way.
Template:
  fields:
    siteTitle: Glue Framework Test Site
  dirs:
    site: "@@SITE_PATH@@/templates"
